version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  # Workflow files stored in the
  # default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: daily
  automerged-updates:
    - match:
      dependency_type: "all"

# Maintain dependencies for npm
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  automerged-updates:
    - match:
      dependency_type: "all"
      update_type: "in_range"
